micronaut:
  server:
    port: 8083
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: jdbc:mysql://localhost:3306/ejemplo
    driverClassName: com.mysql.jdbc.Driver
    username: "garellano"
    password: "garellano"
    schema-generate: NONE
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jpa:
  default:
    entity-scan:
      packages: 'mx.com.metasoft.portal.api.model.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

io:
  micronaut:
    context:
      condition: trace